//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedTickets
    {
        public int ID_Order { get; set; }
        public int ID_Flight { get; set; }
        public int ID_Passanger { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passangers Passangers { get; set; }
    }
}
