//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.BookedTickets = new HashSet<BookedTickets>();
        }
    
        public int ID_Flight { get; set; }
        public string Number_Flight { get; set; }
        public int ID_Route { get; set; }
        public System.DateTime DateTimeDeparture { get; set; }
        public System.TimeSpan FlightTime { get; set; }
        public int ID_Plane { get; set; }
        public int ID_Class { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedTickets> BookedTickets { get; set; }
        public virtual ClassesFlights ClassesFlights { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
