//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Taran_AitportEntities : DbContext
    {
        public Taran_AitportEntities()
            : base("name=Taran_AitportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookedTickets> BookedTickets { get; set; }
        public virtual DbSet<ClassesFlights> ClassesFlights { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Passangers> Passangers { get; set; }
        public virtual DbSet<Plane> Plane { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypesDocuments> TypesDocuments { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
